filename: generated-file.proto
directory:
namespace:
splitBySchema: true
nestEnums: false
typeInEnums: true
includeMessageDocs: true
includeFieldDocs: true
options:
  java_package : org.entur.protobuf
  java_multiple_files : true
customTypeMappings:
  "^CT\\d+_.+$" : "code_table.$0"
  "^ST\\d+_.+$" : "code_table.$0"
  "TimeStampType" : google.protobuf.Timestamp
  "MessageIDType" : int64
  "LogicalSessionIDType" : int64
customNameMappings:

customImports:


